site_name: VR Hands Procedural Grab Pro
#site_url: https://geektechdocs.github.io/vr-hands-procedural-grab-pro/

theme:

  name: material
  #icon:
  #logo: images/logo.svg
  #favicon: images/Icon14x12Gold.svg
  features:
    - toc.integrate
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    #- navigation.indexes
    
  

   

  language: en
  palette:
    scheme: slate
    primary: deep orange
    #primary: white
   

nav:
  - Documentation:
    - Quick Start Guide: index.md
    - Video Tutorials: VRHPGVideoTutorials.md
    - Change Log: changelog.md
    - 📦 Plugin Add-Ons: Addons.md
      
    
  - Plugin Add-Ons:
      - VR 74 Rifle Add-On: Addons.md
      - Climbing Movement Add-On: climbingAddon.md


markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - md_in_html
  - pymdownx.details
  
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - glightbox

extra:
  analytics:
    provider: google
    property: G-F7SLJK3YKK

 
