site_name: VR Hands Procedural Grab Pro
site_url: https://sitename.example
theme:

  name: material
  icon:
  logo: images/logo.svg
  favicon: images/Icon14x12Gold.svg
  features:
    - toc.integrate
    - navigation.expand
   

  language: en
  palette:
    scheme: slate
    primary: orange
    
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.keys

extra_css:
  - stylesheets/extra.css
